### ISSUE TITLE
July 19 Attendance

### ISSUE THREAD

**Issue by gangstead** [nodeschool/dallas#108]

**Comment by samiconductor** [comment]
I _[plan](https://www.youtube.com/watch?v=gn4nRCC9TwQ)_ to attend!

![deepmind-running](https://user-images.githubusercontent.com/603812/28380061-84dfab10-6c7b-11e7-916a-0f4e024ceabe.gif)

**Comment by kwandrews7** [comment]
I'm here patiently waiting for @samiconductor 
![Patiently waiting](https://media1.giphy.com/media/o5oLImoQgGsKY/giphy.gif)

**Comment by gangstead** [comment]
![](https://media.giphy.com/media/3o6gaWqfKO10sNMCEE/giphy.gif)

**Comment by cottjr** [comment]
Ready to go - thanks for hosting :)

**Comment by MightyJoeW** [comment]
Checking in!

**Comment by pizzachip** [comment]
YO - Razoyo is here. Present!

**Comment by Ivy-Moore** [comment]
Here and ready to learn! 😃

**Comment by geenious** [comment]
Checking in! Hello everyone.

**Comment by austinChappell** [comment]
Here.

**Comment by Scuilion** [comment]
Present.

**Comment by rioslupe** [comment]
Here for the pizza.

**Comment by mborders** [comment]
Hither.

**Comment by saurabove** [comment]
Here!

**Comment by susanwinters214** [comment]
Hello

**Comment by kossel** [comment]
howdy

**Comment by enterloper** [comment]
Hello!

**Comment by bgallagher-9** [comment]
Hola

**Comment by dawnomite** [comment]
hi

**Comment by caseylucas** [comment]
here

**Comment by mbazhlekova** [comment]
Hello

**Comment by bzsinger** [comment]
Here

**Comment by chengtseng** [comment]
Hello!

**Comment by samiconductor** [comment]
I made it

**Comment by zalloc** [comment]
Here.

**Comment by pddigital** [comment]
Here.

**Comment by gangstead** [comment]
ITT 24. Headcount 28. Meetup RSVPs 67.
