### ISSUE TITLE
October 2017 Attendance

### ISSUE THREAD

**Issue by samiconductor** [nodeschool/dallas#117]

**Comment by gangstead** [comment]
![](http://static.celebuzz.com/uploads/2013/06/14/super-high-five.gif)

**Comment by tetrakra** [comment]
![image](https://user-images.githubusercontent.com/13581651/31748140-a468f8e4-b436-11e7-9c7a-2fc044233cce.png)

**Comment by pizzachip** [comment]
Paul and Bessie are here from Razoyo (and Razoyo alumna)

**Comment by saaage** [comment]
Stefan was here

**Comment by billott** [comment]
Wow, lots of new faces tonight. Great pan pizza. Thank you, @billdott.

**Comment by ghost** [comment]
Kelley here!

**Comment by lrf0675** [comment]
LaKeisha Turner here

**Comment by prochafilho** [comment]
![image](https://user-images.githubusercontent.com/5936212/31748272-abddf6b4-b437-11e7-9278-41bf0e93e0ed.png)

**Comment by tran82h** [comment]
Great pizza! T here!

**Comment by pizzachip** [comment]
Communication hub: https://github.com/razoyo/cloud-node
Mirror function: https://github.com/razoyo/mm-server

**Comment by shpeacock** [comment]
![image](https://user-images.githubusercontent.com/26874493/31748300-d753fc80-b437-11e7-966d-0740de1bdde3.png)

**Comment by prochafilho** [comment]
here

**Comment by rfleischh** [comment]
here

**Comment by jonbonraki** [comment]
hello

**Comment by gangstead** [comment]
Links for my keepalive project:
- hapi / postgres/ docker backend https://github.com/gangstead/keepalive-service
- angular4 front end https://github.com/gangstead/keepalive-web

- @samiconductor 's project: https://github.com/samiconductor/auth-server

**Comment by gangstead** [comment]
14 in this thread, I counted 25 heads (including one kid), 34 meetup rsvps.
