### ISSUE TITLE
January 2018 Attendance

### ISSUE THREAD

**Issue by michaeledavis-credera** [nodeschool/dallas#122]

**Comment by prochafilho** [comment]
![image](https://user-images.githubusercontent.com/5936212/35074638-71f7913e-fbb4-11e7-82a2-a092f69f7675.png)

**Comment by prochafilho** [comment]
commit -m "attendance: paulo"

**Comment by michaeledavis-credera** [comment]
![happy-new-year-colorful-fireworks-over-city-animated-gif](https://user-images.githubusercontent.com/5984944/35074685-a51bca94-fbb4-11e7-8d4b-b05564fc2aa9.gif)

**Comment by dusteey23** [comment]
I attended

**Comment by kwandrews7** [comment]
![](https://media2.giphy.com/media/l4EoT59vRYdTSi6vS/giphy.gif)

https://aresluna.org/larrys-quest/

**Comment by saaage** [comment]
Present!

**Comment by rjpeek** [comment]
I attended this time, forgot to attend to the last two meetups in 2017.

**Comment by pizzachip** [comment]
Here and present

**Comment by samiconductor** [comment]
here

**Comment by wxb1** [comment]
Hello!

**Comment by rootdevelopper** [comment]
here

**Comment by skipper09** [comment]
Hi!

**Comment by clem-57** [comment]
Cryptopals is cool. Thanks Guys

**Comment by alinaschloesser** [comment]
Here

**Comment by gangstead** [comment]
plus me

**Comment by gangstead** [comment]
14 in this thread, also 14 head count, 30 rsvps
