### ISSUE TITLE
February Attendance 2018

### ISSUE THREAD

**Issue by samiconductor** [nodeschool/dallas#123]
Not here

**Comment by razoyodev** [comment]
Razoyo is here

**Comment by prochafilho** [comment]
here
![here](https://media.giphy.com/media/A40fNMnNPd9yU/giphy.gif)

**Comment by gangstead** [comment]
![](https://media.giphy.com/media/4ayiIWaq2VULC/giphy.gif)

**Comment by starkjoe** [comment]
I bought the pizza :)

**Comment by james-wagner11** [comment]
Here!

**Comment by sdawson26** [comment]
Follow us on twitter!
https://twitter.com/projectatlas_io

**Comment by codes4coffee** [comment]
Here

**Comment by ATechAdventurer** [comment]
Here :octocat:

**Comment by cmarsh940** [comment]
Here

**Comment by charissayj** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by JoelChacon** [comment]
here

**Comment by mnutsch** [comment]
Here

**Comment by mythcard** [comment]
first time here

**Comment by mnutsch** [comment]
Here

**Comment by wxb1** [comment]
Hello?

**Comment by kwandrews7** [comment]
![https://media1.giphy.com/media/IRg7hSjarLJeM/giphy.gif](https://media1.giphy.com/media/IRg7hSjarLJeM/giphy.gif)

**Comment by clem-57** [comment]
Nice place here Atlas. Hope you have another here soon. Thanks for the pizza and fun!

**Comment by michaeledavis** [comment]
https://media3.giphy.com/media/l0HlPtBCscbYiLfR6/200w.gif

**Comment by kwandrews7** [comment]
What @michaeledavis meant to say

![https://media.giphy.com/media/l0HlPtBCscbYiLfR6/giphy.gif](https://media.giphy.com/media/l0HlPtBCscbYiLfR6/giphy.gif)

**Comment by enterloper** [comment]
Yo. Yoooooooo. Yoda. Thanks for hosting Project Atlas!

**Comment by gangstead** [comment]
57 Meetup RSVPS, 25 head count, 20 ITT
