### ISSUE TITLE
April 2018 Attendance

### ISSUE THREAD

**Issue by samiconductor** [nodeschool/dallas#128]

**Comment by pizzachip** [comment]
Present

**Comment by johnpwood** [comment]
here.

**Comment by kwandrews7** [comment]
![](https://m.popkey.co/fba93c/KMzwG_f-maxage-0.gif)

**Comment by clem-57** [comment]
Present today! 
![image](https://user-images.githubusercontent.com/16721922/38964466-9d01ce56-433c-11e8-9822-6fbd09b42647.png)

**Comment by bower5932** [comment]
1st time attendee!

**Comment by hdg-utd** [comment]
present

**Comment by gwgorman** [comment]
this place is great. fantastic speakers too!

**Comment by TannerS** [comment]
:)

**Comment by enterloper** [comment]
Howdy y'all 👋

**Comment by AnalyticsDS** [comment]
glad to see everyone tonight

**Comment by mvodkin** [comment]
Hi! 👋

**Comment by pakoquijano** [comment]
Hey!!

**Comment by Coding-Badly** [comment]
Hi!

**Comment by gangstead** [comment]
![](http://www.omega-level.net/wp-content/uploads/2017/09/clap-your-hands-say-yeah.gif)

**Comment by gangstead** [comment]
15 ITT, 20 head count, 40 Meetup RSVPS
