### ISSUE TITLE
Github security alert

### ISSUE THREAD

**Issue by yasinaydinnet** [nodeschool/dallas#130]
I have been receiving following security warning. Are you considering to update your dependencies?
https://github.com/nodeschool/dallas/network/dependencies

![dallas](https://user-images.githubusercontent.com/1379677/39171962-fc12d35c-47a8-11e8-975b-d4918430ae8d.png)

**Comment by gangstead** [comment]
I went through and deleted all the build files since we are just using jykell to serve it up statically.  Should be fixed now!
