### ISSUE TITLE
May 2018 Attendance

### ISSUE THREAD

**Issue by kwandrews7** [nodeschool/dallas#131]
![](https://media0.giphy.com/media/S5ntyghtbsFwI/giphy.gif)

**Comment by pizzachip** [comment]
Oh yeah.... more node school

**Comment by gangstead** [comment]
![](https://media1.tenor.com/images/6ec9f791dbf19491d60bcfa45931cb90/tenor.gif)

**Comment by johnpwood** [comment]
here.

**Comment by gangstead** [comment]
32 Meetup RSVPS, 10 headcount, 4 ITT
