### ISSUE TITLE
June 2018 Attendance

### ISSUE THREAD

**Issue by samiconductor** [nodeschool/dallas#133]

**Comment by johnpwood** [comment]
here.

**Comment by pizzachip** [comment]
Present and accounted for!

**Comment by charissayj** [comment]
![macon](https://user-images.githubusercontent.com/14130671/41690717-77e34fb2-74bc-11e8-8d66-92e5fbade9aa.gif)

**Comment by clem-57** [comment]
Great place for a great school. Thanks Atlas!

**Comment by skipper09** [comment]
Here.

**Comment by james-wagner11** [comment]
Here!

**Comment by gangstead** [comment]
Sam was here

**Comment by ATechAdventurer** [comment]
Here!

**Comment by cbengtson85** [comment]
👍

**Comment by alinaschloesser** [comment]
here

**Comment by mattbritt** [comment]
present

**Comment by prochafilho** [comment]
![here](https://media.giphy.com/media/pu6PQqp3OA1xu/giphy.gif)

**Comment by erica7** [comment]
present

**Comment by wxb1** [comment]
Present

**Comment by samiconductor** [comment]
Map tiles API key `2rAE6tQ2q3JBnLhH180m`

**Comment by samiconductor** [comment]
15 here / 18 counted / 40 RSVPs
