### ISSUE TITLE
Attendance for May 22, 2015 | International Day

### ISSUE THREAD

**Issue by samiconductor** [nodeschool/dallas#49]
Welcome to International Day!

**Comment by gangstead** [comment]
As they say in Norway - "Hello"\* 

*([90% English speakers](http://en.wikipedia.org/wiki/List_of_countries_by_English-speaking_population))

**Comment by charlesbido** [comment]
Hola! - Charles Bido

**Comment by brentlemons** [comment]
Here

**Comment by amargherio** [comment]
In

**Comment by kwandrews7** [comment]
A man flying in a hot air balloon suddenly realizes he’s lost. He reduces height and spots a man down below. He lowers the balloon further and shouts to get directions, "Excuse me, can you tell me where I am?"

_The man below says: "Yes. You're in a hot air balloon, hovering 30 feet above this field."_

"You must work in Information Technology," says the balloonist.

_"I do" replies the man. "How did you know?"_

"Well," says the balloonist, "everything you have told me is technically correct, but It's of no use to anyone."

_The man below replies, "You must work in management."_

"I do," replies the balloonist, "But how'd you know?"*

"Well", says the man, "you don’t know where you are or where you’re going, but you expect me to be able to help. You’re in the same position you were before we met, but now it’s my fault."

**Comment by ThomRichardson** [comment]
Hey!

**Comment by planetmalone** [comment]
Glad to be here tonight. Ready to learn Node.

**Comment by curtisalexander** [comment]
Thanks for hosting!

**Comment by reidlemons** [comment]
hello

**Comment by ravisharmabhattarai** [comment]
Hello

**Comment by hbaleroni** [comment]
Oi

**Comment by pizzachip** [comment]
Present

**Comment by michaeledavis** [comment]
ATTENDING

**Comment by burin** [comment]
heyo

**Comment by grantlemons** [comment]
Here

**Comment by prochafilho** [comment]
Hello.

**Comment by RGarrett88** [comment]
Sup.

**Comment by gangstead** [comment]
28 RSVPs, 28 Attending, 18 on this thread
