### ISSUE TITLE
Attendance for June 24, 2015

### ISSUE THREAD

**Issue by michaeledavis** [nodeschool/dallas#53]
WOOO ATTENDANCE!

**Comment by caseylucas** [comment]
casey here.  Thank you Credera!

**Comment by gangstead** [comment]
Top Google image search for "Attendance meme":
![image](https://cloud.githubusercontent.com/assets/527760/8344122/88138b12-1aa2-11e5-8071-b53e4b587d32.png)

**Comment by cafreeman** [comment]
Here :)

**Comment by rondagdag** [comment]
Ron is here!

**Comment by z0d14c** [comment]
tomas is here.

**Comment by hcuri** [comment]
Yo estoy aquí

**Comment by amclevy** [comment]
here

**Comment by loganford** [comment]
Here. Thanks!

**Comment by SirJko** [comment]
Thanks! -Jassef

**Comment by samiconductor** [comment]
So full #HotDogPizza

**Comment by nbennette0628** [comment]
I'm not really feeling the #HotDogPizza

**Comment by gangstead** [comment]
12 comments, head count 16, meetup rsvps 45 (what happened?)
