### ISSUE TITLE
July 22 Attendance

### ISSUE THREAD

**Issue by gangstead** [nodeschool/dallas#58]

**Comment by gangstead** [comment]
![image](https://cloud.githubusercontent.com/assets/527760/8827484/88fb26aa-3052-11e5-9125-e383ad06de49.png)

**Comment by amargherio** [comment]
I hope the whole "memes in the checkin posts" becomes a thing. Next time, I'll be prepared.

**Comment by Serisium** [comment]
alfred animate Here!

**Comment by MichaelJCole** [comment]
Hey, thanks!

**Comment by icon6669** [comment]
Thanks for hosting

**Comment by darshanhs90** [comment]
alfred me present

**Comment by jaredtreeves** [comment]
Jared Reeves

**Comment by rondagdag** [comment]
Ron Dagdag

**Comment by pizzachip** [comment]
Razoyo is in da house

**Comment by wbyrnetx** [comment]
William Byrne

**Comment by sethbonnie** [comment]
Seth here

**Comment by bpillai** [comment]
Bharath here

**Comment by prochafilho** [comment]
var present = true;

**Comment by hbaleroni** [comment]
That pizza and code

**Comment by bpillai** [comment]
swathi here

**Comment by ravisharmabhattarai** [comment]
elevator please work

**Comment by ravisharmabhattarai** [comment]
i m here

**Comment by prajwalhkreddy** [comment]
Thanks for hosting!

**Comment by W3bDiva** [comment]
I attended.  More cheese pizza please!  Thanks for having me.

**Comment by timhandtech** [comment]
Thanks for having us, checking in for two

**Comment by kwandrews7** [comment]
![](http://cdn.meme.am/instances2/500x/873597.jpg)

**Comment by michaeledavis** [comment]
I was there!

**Comment by gangstead** [comment]
21 on this thread, @michaeledavis counted 28 in the room and there were 37 RSVPs on meetup.com
