### ISSUE TITLE
August 26th attendance

### ISSUE THREAD

**Issue by gangstead** [nodeschool/dallas#59]

**Comment by michaeledavis** [comment]
_No comment provided._

**Comment by samiconductor** [comment]
I can't promise I'll be there

**Comment by icon6669** [comment]
in like flynn

**Comment by caseylucas** [comment]
here

**Comment by kwandrews7** [comment]
_Small comment provided._

**Comment by bpillai** [comment]
here

**Comment by cottjr** [comment]
here - thanks for hosting...

**Comment by mathewdgardner** [comment]
Hello World

**Comment by sweber6106** [comment]
Here I am.

**Comment by pizzachip** [comment]
Yo.... Razoyo in da house

**Comment by ap-stein** [comment]
Hi.  I joined.  What an awesome intro!!

**Comment by gangstead** [comment]
14 people commenting (including 2 that mistakenly opened issues instead of posting), 35 RSVPs, counted around 20ish in the room.
