### ISSUE TITLE
September 23rd attendance

### ISSUE THREAD

**Issue by michaeledavis** [nodeschool/dallas#62]

**Comment by caseylucas** [comment]
here

**Comment by gangstead** [comment]
![](http://i.imgur.com/c8B5VqR.gif)

**Comment by michaeledavis** [comment]
Present.... and a little uncomfortable after the last check-in.

**Comment by samiconductor** [comment]
gross

**Comment by sweber6106** [comment]
I'm here.

**Comment by prochafilho** [comment]
Checking in...

**Comment by gaker** [comment]
Visiting from Missouri

**Comment by subbramanil** [comment]
First time here.. Its awesome!!

**Comment by davidpetrey** [comment]
here

**Comment by ghost** [comment]
Im here...

![](http://media.giphy.com/media/Zo9ACzmJgoqRy/giphy.gif)

**Comment by ebony-j** [comment]
here

**Comment by gangstead** [comment]
12 on this thread (including the person who started a new issue instead of commenting here). I counted 18 heads at the meeting and 27 rsvps on meetup.com
