### ISSUE TITLE
12/2/15 Attendance

### ISSUE THREAD

**Issue by michaeledavis** [nodeschool/dallas#67]

**Comment by caseylucas** [comment]
thanks for the pizza credera!

**Comment by conrman** [comment]
+1 🍕

**Comment by gangstead** [comment]
![bring it](http://itgeek.aiksite.com/wp-content/uploads/2014/03/just-bring-it.jpg)

**Comment by ehis** [comment]
+1

**Comment by odran037** [comment]
First time here. Looking forward to the next one.

**Comment by PWAckerman** [comment]
I am here.

**Comment by michaeledavis** [comment]
👍

**Comment by hh83917** [comment]
Present!

**Comment by treychadwell** [comment]
+1

**Comment by jtrevag** [comment]
Ayyeee lmao. (Thanks for the pizza)

**Comment by drbortel** [comment]
Greetings

**Comment by simply-daniel** [comment]
Here

**Comment by agoytia** [comment]
Node + Pizaa = bomb.com

**Comment by zalloc** [comment]
Thank you Credera for hosting and the food.

**Comment by gangstead** [comment]
14 on this thread, I counted 18 heads at the meeting and 32 rsvps on meetup.com
