### ISSUE TITLE
2016-01-20 Attendance

### ISSUE THREAD

**Issue by gangstead** [nodeschool/dallas#71]
Attendees tonight leave a comment, so we know who actually showed up versus just RSVP'ing on Meetup.

![image](http://vignette2.wikia.nocookie.net/animaljam/images/8/84/Whale-Hello.gif)

**Comment by timhandtech** [comment]
I'll be there as long as that's alright

Timothy Hand


Technical Recruiter

(972)813-0418

Timothy.Hand@modis.com

LinkedIn: https://www.linkedin.com/pub/timothy-hand/76/a71/10a

**Comment by mathewdgardner** [comment]
+1

**Comment by zbarnes757** [comment]
here

**Comment by robbiedhickey** [comment]
Present.

**Comment by oparamo** [comment]
+1 :turtle:

**Comment by shayneo** [comment]
Arrrg!

**Comment by paulqlove** [comment]
#

**Comment by hanthom** [comment]
What is this place?

**Comment by odran037** [comment]
```
function hasAttended(confirmation) {
  return confirmation ? true : false;
}
hasAttended('I did');
```

**Comment by jaredhensley** [comment]
yeah buddy!

**Comment by PWAckerman** [comment]
Here!

**Comment by JaiGhanekar** [comment]
+1

**Comment by leongaban** [comment]
`WOOT!`

**Comment by johnazre** [comment]
I'm here

**Comment by adkins2010** [comment]
We are the music makers and we are the dreamers of dreams.

**Comment by bruceblay** [comment]
preach

**Comment by hh83917** [comment]
Present!

**Comment by dominiquejane** [comment]
comment

**Comment by bryantson** [comment]
++ Attendance

**Comment by georgesunil81** [comment]
My very first meetup. Didn't disappoint. Happy to learn and test Hapi!

**Comment by crbrooks** [comment]
here!

**Comment by kwandrews7** [comment]
![](https://media.giphy.com/media/ukMiDlCmdv2og/giphy.gif)

**Comment by michaeledavis** [comment]
![](https://media.giphy.com/media/gU25raLP4pUu4/giphy.gif)

**Comment by samiconductor** [comment]
![It's working](http://iruntheinternet.com/lulzdump/images/star-wars-terminator-2-mash-up-its-working-anakin-skywalker-14098428930.gif?id=337)

**Comment by rezahell** [comment]
Reza+

**Comment by caseylucas** [comment]
thanks vinli

**Comment by prochafilho** [comment]
+1

**Comment by gangstead** [comment]
**edited**
28 in this thread, I counted 30 in person, plus maybe 4 Vinli employees who think they are above that, 40 Meetup RSVPs.

**Comment by TXredking** [comment]
@gangstead I apologize just remembered to comment on this.
