### ISSUE TITLE
2016-02-17 Attendance

### ISSUE THREAD

**Issue by kwandrews7** [nodeschool/dallas#75]
Attendees tonight leave a comment, so we know who actually showed up versus just RSVP'ing on Meetup.

![](https://media.giphy.com/media/brsEO1JayBVja/giphy.gif)

**Comment by drbortel** [comment]
here

**Comment by caseylucas** [comment]
yo

**Comment by latish** [comment]
here

**Comment by bpillai** [comment]
here

**Comment by jtrevag** [comment]
`<img style="-webkit-user-select: none" src="http://p.fod4.com/p/media/15622856b6/5x8xefLwQaWQND3oZPvw_Simpsons%20Stare.gif">`

**Comment by jtrevag** [comment]
yellow
![image](https://cloud.githubusercontent.com/assets/5503381/13130359/06ac8192-d5a9-11e5-88ad-83a441eb7cc4.png)

**Comment by zalloc** [comment]
Here.

**Comment by baruchvlz** [comment]
Here.

**Comment by mathewdgardner** [comment]
here

**Comment by JoSmoBN** [comment]
Here.

**Comment by pizzachip** [comment]
Razoyo is in da house

**Comment by zbarnes757** [comment]
here!

**Comment by Spenc84** [comment]
Here

**Comment by lastcoolnameleft** [comment]
![tumblr_inline_nsqt0uqenn1t0q5m4_500](https://cloud.githubusercontent.com/assets/686999/13130446/ab4276da-d5a9-11e5-8df7-653e07650855.gif)

**Comment by fodderotter** [comment]
Here.

**Comment by sjmorrow** [comment]
![Waving](http://vignette2.wikia.nocookie.net/olympians/images/2/25/Pikachu_waving.gif/revision/latest?cb=20150411214455)

**Comment by nvankems** [comment]
Hello, fellow humans!

**Comment by garciae** [comment]
Here.

**Comment by ecropolis** [comment]
Here!

**Comment by lesliesmith** [comment]
Here

**Comment by akoneru-modiv** [comment]
here!

**Comment by sakella1986** [comment]
here

**Comment by BenMGilman** [comment]
Learn me react

**Comment by ghost** [comment]
here

**Comment by HenryDev** [comment]
here

**Comment by michaeledavis** [comment]
Here!

**Comment by gangstead** [comment]
![image](https://cloud.githubusercontent.com/assets/527760/13131048/96297870-d5ae-11e5-9b35-1b9ecc038b5d.png)

**Comment by bennettj** [comment]
here

**Comment by samiconductor** [comment]
+1

**Comment by TXredking** [comment]
Here!

**Comment by gangstead** [comment]
30 here, I counted 45 at the meeting 79 rsvps on meetup.com
