### ISSUE TITLE
2016-04-20 Attendance

### ISSUE THREAD

**Issue by michaeledavis** [nodeschool/dallas#81]

**Comment by caseylucas** [comment]
Here!

**Comment by prochafilho** [comment]
Dude...

**Comment by pizzachip** [comment]
Unlike Beau Bergdahl - present and accounted for

**Comment by kwandrews7** [comment]
![commit strip](http://www.commitstrip.com/wp-content/uploads/2016/04/Strip-Openspace-kit-650-finalenglish.jpg)

**Comment by samiconductor** [comment]
almost... there... just... gotta...

![giphy](https://cloud.githubusercontent.com/assets/603812/14693922/374c9358-0729-11e6-9d9a-48986f075ccd.gif)

**Comment by vcheruk** [comment]
Here

**Comment by gangstead** [comment]
![](https://uploads.disquscdn.com/images/f282d09d65a492221ef0e20c48408a05e2681a9dafa29c0f5403c2d07cb1b0d2.gif)

**Comment by gangstead** [comment]
22 rsvps, 12 heads at the meetup, 8 in this thread.
