### ISSUE TITLE
Attendance for 6/15/2016

### ISSUE THREAD

**Issue by michaeledavis-credera** [nodeschool/dallas#85]
Comment below to have your attendance counted!

**Comment by samiconductor** [comment]
1! ah ah ah

**Comment by prochafilho** [comment]
Hi mom!

**Comment by kwandrews7** [comment]
![Hi](https://media.giphy.com/media/vYtDDrgTXyrm0/giphy.gif)

**Comment by michaeledavis** [comment]
![](http://i.imgur.com/tHvSjqQ.jpg)

**Comment by codyw9524** [comment]
Hiya!

**Comment by masonhensley** [comment]
Here!

**Comment by gregspagnolo** [comment]
![image](https://cloud.githubusercontent.com/assets/1299405/16101724/3d180642-332e-11e6-95ec-67f50a7bdb18.png)

**Comment by ntxtthomas** [comment]
present

**Comment by samiconductor** [comment]
35 RSVP, 13 counted, 8 comments

**Comment by gp1864** [comment]
I am here.

**Comment by W3bDiva** [comment]
Thanks for your help.

**Comment by michaeledavis** [comment]
35 RSVP, 13 counted, 10 comments
