### ISSUE TITLE
Attendance for 7/20/2016

### ISSUE THREAD

**Issue by samiconductor** [nodeschool/dallas#88]

**Comment by mathewdgardner** [comment]
+1

**Comment by n-boehmisch** [comment]
+
![image](https://cloud.githubusercontent.com/assets/15949667/17008299/907043ca-4eb5-11e6-86c4-87909e247441.png)

**Comment by gangstead** [comment]
Yall should really checkout this movie: ![](http://www.forum-uncut.dk/adm_pic/PostApo/RobotJox.jpg)

**Comment by shayneo** [comment]
aye!

**Comment by michaeledavis-credera** [comment]
**YO**

**Comment by prochafilho** [comment]
+1

**Comment by michaeledavis** [comment]
**YO**

**Comment by ciro-account** [comment]
Present

**Comment by caseylucas** [comment]
h _e_ **r** **_e_**

**Comment by gp1864** [comment]
I'm too.

**Comment by gangstead** [comment]
9 here, 12 head count, 18 rsvps

**Comment by jeradamundsen** [comment]
good food, good code, and good vibes
