### ISSUE TITLE
October 19th Attendance

### ISSUE THREAD

**Issue by samiconductor** [nodeschool/dallas#93]
Cheers! 🍻

**Comment by gangstead** [comment]
![](http://i.kinja-img.com/gawker-media/image/upload/t_original/e5wibpgsnfghfekvn2kf.gif)

**Comment by pizzachip** [comment]
In da house!

**Comment by dshaneg** [comment]
GameStop representin'

**Comment by caseylucas** [comment]
here

**Comment by gp1864** [comment]
I am here.

**Comment by getashish** [comment]
From Gamestop

**Comment by bchukwuma** [comment]
つ ◕_◕ ༽つ

**Comment by gangstead** [comment]
20 RSVPs, headcount 15, 8 in this thread

**Comment by gangstead** [comment]
Did anyone leave behind an Acer power cable?
![img_20161019_214818](https://cloud.githubusercontent.com/assets/527760/19544651/0748c0da-9646-11e6-80f1-e9dccebd7e54.jpg)

**Comment by gangstead** [comment]
## Future of Nodeschool discussion notes

### Ideas
- Having a workshop tract and a giving-back-to-nodeschool tract for the more advanced people
- Deep dive on the subject before starting the workshop
- Project that spans a couple meetups that everyone works on together

#### Giving back ideas
- Fix issues
- Possibly fork abandoned workshoppers into nodeschool
- Build new modules
  - ie unit testing
  - finish [commander](https://github.com/gangstead/comder) one we started in 2015
- Come up with a better way to communicate ideas for nodeschool (presentations, venues, workshoppers to do, workshoppers to create).  Current preferred method is [creating a github issue](https://github.com/nodeschool/dallas/issues), but that's not very well known.

Keep doing
- News
- Coding / hands on at every meetup

Start doing
- Meetups North of "The Wall" (George Bush Turn Pike)
  - Need volunteers for locations
- Presentations related to the workshop/activity of the night
  - Need volunteers for presenters
  - Any format is ok - regular slide presentation or lead a live coding workshop / walk through
  - keep them brief
  - ideas:
    - yarn
    - docker at Vinli
